name: deploy
on: [push]

env:
  EMSDK_VERSION: 3.1.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: emsdk-cache
          key: ${{env.EMSDK_VERSION}}-${{runner.os}}
      - name: Set up Emscripten SDK
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EMSDK_VERSION}}
          actions-cache-folder: emsdk-cache
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up Meson
        run: |
          python -m pip install meson==0.61.1
          python -m pip install ninja
      - name: Run test
        run: |
          meson setup _build/test
          meson test -C _build/test
      - name: Build
        run: ./build-all-variant.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
